### ISSUE TITLE
Checking if avisdk python library is present breaks in virtual environments

### ISSUE THREAD

**Issue by skinitimski** [avinetworks/ansible-role-avisdk#16]
The following change, introduced in 17.2.2, which adds a check for the avisdk package, does not work in a [virtual environment](https://virtualenv.pypa.io/en/stable/), due to an absolute path being used for the python executable.

https://github.com/avinetworks/ansible-role-avisdk/commit/da32139c0599c9e103cfe0f811f5e935bcf5d6d2#diff-2444ad0870f91f17ca6c2a5e96b26823

Steps to reproduce (sort of):
`virtualenv venv
. venv/bin/activate
pip install avisdk
python -c 'from avi.sdk.avi_api import ApiSession' # works
/usr/bin/python -c 'from avi.sdk.avi_api import ApiSession' # fails
`

Changing `/usr/bin/python` to `python` in `tasks/main.yml` results in success with a virtual environment.

**Comment by grastogi23** [comment]
updated the 17.2.2 with the reverted check for avisdk. We will create a new release with proper fix that can work in different environments.
