### ISSUE TITLE
Unable to import .... due to more than 255 arguments

### ISSUE THREAD

**Issue by ciobancai** [avinetworks/ansible-role-avisdk#195]
Hi,

We have encountered the below error when we tried to use "avi_serviceenginegroup" with ansible-role-avisdk version 20.1.6 , this problem doesn't appear on 20.1.5 . 
```
{
  "msg": "Unable to import avi_serviceenginegroup due to more than 255 arguments", 
  "_ansible_no_log": false
}

```
Based to this commit https://github.com/avinetworks/ansible-role-avisdk/commit/81b4ab8874ace316cf86266b863291219696bd9c#diff-6a3b6c4711b1eb94c752489c7b99560f57058704226a9fe02df92788d56604fd the library/avi_serviceenginegroup.py has more than 255 arguments.

Multiple runs made in different environments using ansible 2.8 with python 2.7

```
ansible-playbook 2.8.20
  config file = /go-agent/pipelines/ie2lab_avic_lab/ansible.cfg
  configured module search path = [u'/usr/local/ansible/modules/core', u'/usr/local/ansible/modules/extra', u'/usr/share/ansible', u'/go-agent/pipelines/ie2lab_avic_lab/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.18 (default, May  3 2020, 22:58:11) [GCC 8.3.0]
Using /go-agent/pipelines/ie2lab_avic_lab/ansible.cfg as config file
```

It is possible to look over it and apply a fix for python >= 2.6 ?

**Comment by sabandi** [comment]
Hi @ciobancai ,

This is a python runtime limitation where we cannot have a module with more than 255 args.  It is fixed in Python >= 3.7.
You can use our role with the above mentioned Python versions to get past this issue.

Please let me know if you have any questions.

**Comment by ciobancai** [comment]
Hi @sabandi,

Thank you for the reply, for the moment we can not migrate to Python >= 3.7 (we will discuss internally and see when it will be possible) until then we will use the ansible-role-sdk 20.1.5 . As a suggestion it is possible the README to be updated just in case somebody will have the same problem to know.

**Comment by sabandi** [comment]
Thanks for the feedback @ciobancai . We are already working on shipping our Anisble assets as collections and have a task to add this note explicitly to the readme.
