### ISSUE TITLE
NameError: global name 'avi_common_argument_spec' is not defined

### ISSUE THREAD

**Issue by dflorea01** [avinetworks/ansible-role-avisdk#63]
On macOS Using AnsiballZ_avi_healthmonitor.py is throwing this error:

<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python@2/bin/python2.7 /Users/123223/.ansible/tmp/ansible-tmp-1546636878.27-257638194948148/AnsiballZ_avi
_healthmonitor.py && sleep 0'
 36498 1546636878.39933: opening command with Popen()
 36498 1546636878.40287: done running command with Popen()
 36498 1546636878.40318: getting output with communicate()
 36498 1546636878.49552: done communicating
 36498 1546636878.49560: done with local.exec_command()
 36498 1546636878.49575: _low_level_execute_command() done: rc=1, stdout=, stderr=Traceback (most recent call last):
  File "/Users/123223/.ansible/tmp/ansible-tmp-1546636878.27-257638194948148/AnsiballZ_avi_healthmonitor.py", line 113, in <module>
    _ansiballz_main()

  File "/Users/123223/.ansible/tmp/ansible-tmp-1546636878.27-257638194948148/AnsiballZ_avi_healthmonitor.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/123223/.ansible/tmp/ansible-tmp-1546636878.27-257638194948148/AnsiballZ_avi_healthmonitor.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/var/folders/nf/dfwgrk2s7zq2qmz9wy4d8q18nsnvjz/T/ansible_avi_healthmonitor_payload_ze3noB/__main__.py", line 213, in <module>
  File "/var/folders/nf/dfwgrk2s7zq2qmz9wy4d8q18nsnvjz/T/ansible_avi_healthmonitor_payload_ze3noB/__main__.py", line 201, in main
NameError: global name 'avi_common_argument_spec' is not defined

 36459 1546636878.51350: getting the next task for host localhost
 36459 1546636878.51357: done getting next task for host localhost
 36459 1546636878.51361:  ^ task is: None
 36459 1546636878.51368:  ^ state is: HOST STATE: block=3, task=8, rescue=0, always=0, run_state=ITERATING_COMPLETE, fail_state=FAILED_TASKS, pending_se
tup=False, tasks child state? (None), rescue child state? (None), always child state? (None), did rescue? False, did start at task? False
The full traceback is:
Traceback (most recent call last):
  File "/Users/123223/.ansible/tmp/ansible-tmp-1546636878.27-257638194948148/AnsiballZ_avi_healthmonitor.py", line 113, in <module>

    _ansiballz_main()
  File "/Users/123223/.ansible/tmp/ansible-tmp-1546636878.27-257638194948148/AnsiballZ_avi_healthmonitor.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/123223/.ansible/tmp/ansible-tmp-1546636878.27-257638194948148/AnsiballZ_avi_healthmonitor.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/var/folders/nf/dfwgrk2s7zq2qmz9wy4d8q18nsnvjz/T/ansible_avi_healthmonitor_payload_ze3noB/__main__.py", line 213, in <module>
  File "/var/folders/nf/dfwgrk2s7zq2qmz9wy4d8q18nsnvjz/T/ansible_avi_healthmonitor_payload_ze3noB/__main__.py", line 201, in main
NameError: global name 'avi_common_argument_spec' is not defined

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/123223/.ansible/tmp/ansible-tmp-1546636878.27-257638194948148/AnsiballZ_avi
_healthmonitor.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/Users/123223/.ansible/tmp/ansible-tmp-1546636878.27-257638194948148/Ansi
ballZ_avi_healthmonitor.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/123223/.ansib
le/tmp/ansible-tmp-1546636878.27-257638194948148/AnsiballZ_avi_healthmonitor.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, modul
e, MOD_DESC)\n  File \"/var/folders/nf/dfwgrk2s7zq2qmz9wy4d8q18nsnvjz/T/ansible_avi_healthmonitor_payload_ze3noB/__main__.py\", line 213, in <module>\n
 File \"/var/folders/nf/dfwgrk2s7zq2qmz9wy4d8q18nsnvjz/T/ansible_avi_healthmonitor_payload_ze3noB/__main__.py\", line 201, in main\nNameError: global na
me 'avi_common_argument_spec' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1

ansible-galaxy list
- avinetworks.avise-csp, 18.1.3
- avinetworks.avise, 18.1.5
- avinetworks.avisdk, 18.2.1
- avinetworks.aviconfig, 18.1.5
- avinetworks.avicontroller-csp, 18.1.3
- avinetworks.avicontroller-vmware, 18.1.3
- avinetworks.avicontroller-azure, 18.1.3
- avinetworks.avicontroller, 18.1.5

**Comment by ericsysmin** [comment]
@dflorea01 is this still an issue with the latest version for you?

**Comment by kenerwin88** [comment]
Why hello there @ericsysmin, I'm hitting this issue as well. :)

**Comment by ericsysmin** [comment]
> Why hello there @ericsysmin, I'm hitting this issue as well. :)
> 
> Latest version pulled from ansible-galaxy, ansible 2.8.5

You've already installed `avisdk >= 18.2.5` in your python virtualenv right?

**Comment by mchekuri-incomm** [comment]
Hello @ericsysmin, 
I'm using avisdk 22.1.2 and Im seeing the same error mentioned by original poster: "NameError: name 'avi_common_argument_spec' is not defined"

Any suggestions please? This is happening only on certain AVI controllers. With other AVI controllers it works fine.

**Comment by mchekuri-incomm** [comment]
Running pip install avisdk --upgrade resolved it for me. Thank you.

**Comment by chaitanyaavi** [comment]
Hi @mchekuri-incomm 
We have moved this in vmware.alb collections and stop maintaining this role. Can you please try with vmware.alb collections ?

**Comment by mchekuri-incomm** [comment]
@chaitanyaavi thanks for your comment. Had more issues again with avisdk. Had to replace it with vmware.alb collection and it works like charm. thank you.
